import { SlideData } from '@/types';

export const heroRoyalBlueImg = '/images/hero_royal_blue_1788292230828.jpg';
export const heroIvoryImg = '/images/hero_ivory_suit_1788292246165.jpg';

export const SLIDES_DATA: SlideData[] = [
  {
    id: 1,
    tag: "FESTIVE EDIT • SIGNATURE ROYAL BLUE",
    headlineStart: "Pure Handloom Woven",
    headlineItalic: "Into Royal Grace",
    brandTitle: "ZAYMERA COUTURE",
    brandSubtitle: "ROYAL SAPPHIRE TREE-MOTIF ANARKALI",
    description:
      "Sculpted in pure breathable handloom cotton featuring artisan white tree-of-life threadwork embroidery and delicate scalloped borders.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?category=festive-wear",
    secondaryCta: "View Details",
    secondaryHref: "/shop",
    image: heroRoyalBlueImg,
    theme: "dark-gold",
    productName: "Zaymera Royal Sapphire Tree-Motif Anarkali Suit",
    productPrice: "₹3,999",
    productSlug: "zaymera-royal-sapphire-tree-motif-anarkali",
    badge: "Bestseller Signature Edit",
    accent: "100% Pure Handloom Cotton",
    location: "Haute Couture Atelier",
  },
  {
    id: 2,
    tag: "BRIDAL TROUSSAU • PEARL IVORY",
    headlineStart: "Timeless Scalloped",
    headlineItalic: "Ivory Resham Suit",
    brandTitle: "ZAYMERA BRIDAL",
    brandSubtitle: "PEARL IVORY SCALLOPED ENSEMBLE",
    description:
      "Ethereal ivory silhouette with botanical tree motifs along the flared hem and matching head-draped scalloped dupatta.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?category=wedding-collection",
    secondaryCta: "View Lookbook",
    secondaryHref: "/lookbook",
    image: heroIvoryImg,
    theme: "light-editorial",
    productName: "Zaymera Pearl Ivory Scalloped Anarkali Suit",
    productPrice: "₹4,299",
    productSlug: "zaymera-pearl-ivory-scalloped-anarkali",
    badge: "Tone-on-Tone Artisan Resham",
    accent: "Ceremony Edition",
    location: "Bridal Atelier",
  },
  {
    id: 3,
    tag: "ATELIER 2026 • CEREMONIAL SANCTUARY",
    headlineStart: "Haute Couture &",
    headlineItalic: "Bridal Sanctuary",
    brandTitle: "ZAYMERA",
    brandSubtitle: "HAUTE COUTURE & DESIGNER HUB",
    description:
      "A serene sanctuary of quiet luxury, handcrafted bridal churidars, and pure artisan handloom fabrics.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?collection=flagship",
    secondaryCta: "Explore Atelier",
    secondaryHref: "/store-tour",
    image: "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?q=80&w=2000&auto=format&fit=crop",
    theme: "night-architectural",
    productName: "Zaymera Flagship Bridal & Designer Hub",
    productPrice: "Boutique Experience",
    productSlug: "zaymera-flagship-destination",
    badge: "Flagship Atelier",
    accent: "Ceremony Edition 2026",
    location: "Fashion Boulevard Landmark",
  },
  {
    id: 4,
    tag: "UNSTITCHED FABRICS • CHANDERI",
    headlineStart: "Bespoke Silks for",
    headlineItalic: "Your Silhouette",
    brandTitle: "ZAYMERA ATELIER",
    brandSubtitle: "CHANDERI SILK SUITE",
    description:
      "Three-piece unstitched Chanderi silk and breathable cotton fabric sets for custom tailoring.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?category=unstitched-material",
    secondaryCta: "Custom Sizing",
    secondaryHref: "/contact",
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=2000&auto=format&fit=crop",
    theme: "warm-amber",
    productName: "Zaymera Chanderi Silk Material Set",
    productPrice: "₹2,799",
    productSlug: "zaymera-unstitched-chanderi-silk-material",
    badge: "3-Piece Fabric with Zari Dupatta",
    accent: "Unstitched Material",
    location: "Unstitched Gallery",
  }
];
