import { SlideData } from '@/types';

export const heroRoyalBlueImg = '/images/hero_royal_blue_1788292230828.jpg';
export const heroIvoryImg = '/images/hero_ivory_suit_1788292246165.jpg';
export const heroEmeraldImg = '/images/hero_emerald_suit.jpg';
export const heroRubyImg = '/images/hero_ruby_dress.jpg';

export const SLIDES_DATA: SlideData[] = [
  {
    id: 1,
    tag: "FESTIVE EDIT • SIGNATURE ROYAL BLUE",
    headlineStart: "Pure Handloom Woven",
    headlineItalic: "Into Royal Grace",
    brandTitle: "ZAYMERA COUTURE",
    brandSubtitle: "ROYAL SAPPHIRE TREE-MOTIF ANARKALI",
    description:
      "Sculpted in pure breathable handloom cotton featuring artisan white tree-of-life threadwork embroidery and delicate scalloped borders.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?category=festive-wear",
    secondaryCta: "View Details",
    secondaryHref: "/shop",
    image: heroRoyalBlueImg,
    theme: "dark-gold",
    productName: "Zaymera Royal Sapphire Tree-Motif Anarkali Suit",
    productPrice: "₹3,999",
    productSlug: "zaymera-royal-sapphire-tree-motif-anarkali",
    badge: "Bestseller Signature Edit",
    accent: "100% Pure Handloom Cotton",
    location: "Haute Couture Atelier",
  },
  {
    id: 2,
    tag: "BRIDAL TROUSSEAU • PEARL IVORY",
    headlineStart: "Timeless Scalloped",
    headlineItalic: "Ivory Resham Suit",
    brandTitle: "ZAYMERA BRIDAL",
    brandSubtitle: "PEARL IVORY SCALLOPED ENSEMBLE",
    description:
      "Ethereal ivory silhouette with botanical tree motifs along the flared hem and matching head-draped scalloped dupatta.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?category=wedding-collection",
    secondaryCta: "View Lookbook",
    secondaryHref: "/lookbook",
    image: heroIvoryImg,
    theme: "light-editorial",
    productName: "Zaymera Pearl Ivory Scalloped Anarkali Suit",
    productPrice: "₹4,299",
    productSlug: "zaymera-pearl-ivory-scalloped-anarkali",
    badge: "Tone-on-Tone Artisan Resham",
    accent: "Ceremony Edition",
    location: "Bridal Atelier",
  },
  {
    id: 3,
    tag: "ROYAL HERITAGE • EMERALD COUTURE",
    headlineStart: "Artisan Handcrafted",
    headlineItalic: "Emerald Zardozi Suit",
    brandTitle: "ZAYMERA COUTURE",
    brandSubtitle: "EMERALD GOLD ZARDOZI ANARKALI",
    description:
      "Regal emerald green pure silk silhouette adorned with intricate gold zardozi embroidery and an opulent scalloped sheer dupatta.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?category=festive-wear",
    secondaryCta: "Explore Collection",
    secondaryHref: "/products",
    image: heroEmeraldImg,
    theme: "night-architectural",
    productName: "Zaymera Emerald Royal Zardozi Anarkali Suit",
    productPrice: "₹4,599",
    productSlug: "zaymera-emerald-royal-zardozi-anarkali",
    badge: "Handcrafted Zardozi Edit",
    accent: "Pure Silk & Gold Zari",
    location: "Royal Heritage Atelier",
  },
  {
    id: 4,
    tag: "BRIDAL HERITAGE • RUBY CRIMSON",
    headlineStart: "Bespoke Ceremonial",
    headlineItalic: "Ruby Bridal Ensemble",
    brandTitle: "ZAYMERA BRIDAL",
    brandSubtitle: "CRIMSON ZARI BRIDAL SUITE",
    description:
      "Masterfully woven ruby crimson bridal ensemble accented with heirloom gold threadwork, delicate sheer veil, and majestic flare.",
    primaryCta: "SHOP NOW",
    primaryHref: "/shop?category=wedding-collection",
    secondaryCta: "View Details",
    secondaryHref: "/products",
    image: heroRubyImg,
    theme: "warm-amber",
    productName: "Zaymera Crimson Heirloom Bridal Suit",
    productPrice: "₹4,999",
    productSlug: "zaymera-crimson-heirloom-bridal-suit",
    badge: "Master Artisan Bridal",
    accent: "Heirloom Gold Threadwork",
    location: "Bridal Couture Gallery",
  }
];
